// Real top-4-tier English pyramid data (2025-26 season): Premier League (20), Championship
// (24), League One (24), League Two (24) — 92 real clubs, ordered by tier. Curated pools,
// mirroring the player-identity precedent (#142/#143): explicit data over fuzzy auto-discovery.
// @spec BADGE-004,BADGE-007,BADGE-008,BADGE-009
// Co-located module (not inline in models.ts) — mirrors the curated player-identity pools
// pattern for large static data tables.

type Tier = 'PL' | 'CHAMP' | 'L1' | 'L2';

const England92: { key: string; name: string; tier: Tier }[] = [
  { key: 'arsenal', name: 'Arsenal', tier: 'PL' },
  { key: 'aston-villa', name: 'Aston Villa', tier: 'PL' },
  { key: 'bournemouth', name: 'Bournemouth', tier: 'PL' },
  { key: 'brentford', name: 'Brentford', tier: 'PL' },
  { key: 'brighton-hove-albion', name: 'Brighton & Hove Albion', tier: 'PL' },
  { key: 'burnley', name: 'Burnley', tier: 'PL' },
  { key: 'chelsea', name: 'Chelsea', tier: 'PL' },
  { key: 'crystal-palace', name: 'Crystal Palace', tier: 'PL' },
  { key: 'everton', name: 'Everton', tier: 'PL' },
  { key: 'fulham', name: 'Fulham', tier: 'PL' },
  { key: 'leeds-united', name: 'Leeds United', tier: 'PL' },
  { key: 'liverpool', name: 'Liverpool', tier: 'PL' },
  { key: 'manchester-city', name: 'Manchester City', tier: 'PL' },
  { key: 'manchester-united', name: 'Manchester United', tier: 'PL' },
  { key: 'newcastle-united', name: 'Newcastle United', tier: 'PL' },
  { key: 'nottingham-forest', name: 'Nottingham Forest', tier: 'PL' },
  { key: 'sunderland', name: 'Sunderland', tier: 'PL' },
  { key: 'tottenham-hotspur', name: 'Tottenham Hotspur', tier: 'PL' },
  { key: 'west-ham-united', name: 'West Ham United', tier: 'PL' },
  { key: 'wolverhampton-wanderers', name: 'Wolverhampton Wanderers', tier: 'PL' },
  { key: 'birmingham-city', name: 'Birmingham City', tier: 'CHAMP' },
  { key: 'blackburn-rovers', name: 'Blackburn Rovers', tier: 'CHAMP' },
  { key: 'bristol-city', name: 'Bristol City', tier: 'CHAMP' },
  { key: 'charlton-athletic', name: 'Charlton Athletic', tier: 'CHAMP' },
  { key: 'coventry-city', name: 'Coventry City', tier: 'CHAMP' },
  { key: 'derby-county', name: 'Derby County', tier: 'CHAMP' },
  { key: 'hull-city', name: 'Hull City', tier: 'CHAMP' },
  { key: 'ipswich-town', name: 'Ipswich Town', tier: 'CHAMP' },
  { key: 'leicester-city', name: 'Leicester City', tier: 'CHAMP' },
  { key: 'middlesbrough', name: 'Middlesbrough', tier: 'CHAMP' },
  { key: 'millwall', name: 'Millwall', tier: 'CHAMP' },
  { key: 'norwich-city', name: 'Norwich City', tier: 'CHAMP' },
  { key: 'oxford-united', name: 'Oxford United', tier: 'CHAMP' },
  { key: 'portsmouth', name: 'Portsmouth', tier: 'CHAMP' },
  { key: 'preston-north-end', name: 'Preston North End', tier: 'CHAMP' },
  { key: 'queens-park-rangers', name: 'Queens Park Rangers', tier: 'CHAMP' },
  { key: 'sheffield-united', name: 'Sheffield United', tier: 'CHAMP' },
  { key: 'sheffield-wednesday', name: 'Sheffield Wednesday', tier: 'CHAMP' },
  { key: 'southampton', name: 'Southampton', tier: 'CHAMP' },
  { key: 'stoke-city', name: 'Stoke City', tier: 'CHAMP' },
  { key: 'swansea-city', name: 'Swansea City', tier: 'CHAMP' },
  { key: 'watford', name: 'Watford', tier: 'CHAMP' },
  { key: 'west-bromwich-albion', name: 'West Bromwich Albion', tier: 'CHAMP' },
  { key: 'wrexham', name: 'Wrexham', tier: 'CHAMP' },
  { key: 'afc-wimbledon', name: 'AFC Wimbledon', tier: 'L1' },
  { key: 'barnsley', name: 'Barnsley', tier: 'L1' },
  { key: 'blackpool', name: 'Blackpool', tier: 'L1' },
  { key: 'bolton-wanderers', name: 'Bolton Wanderers', tier: 'L1' },
  { key: 'bradford-city', name: 'Bradford City', tier: 'L1' },
  { key: 'burton-albion', name: 'Burton Albion', tier: 'L1' },
  { key: 'cardiff-city', name: 'Cardiff City', tier: 'L1' },
  { key: 'doncaster-rovers', name: 'Doncaster Rovers', tier: 'L1' },
  { key: 'exeter-city', name: 'Exeter City', tier: 'L1' },
  { key: 'huddersfield-town', name: 'Huddersfield Town', tier: 'L1' },
  { key: 'leyton-orient', name: 'Leyton Orient', tier: 'L1' },
  { key: 'lincoln-city', name: 'Lincoln City', tier: 'L1' },
  { key: 'luton-town', name: 'Luton Town', tier: 'L1' },
  { key: 'mansfield-town', name: 'Mansfield Town', tier: 'L1' },
  { key: 'northampton-town', name: 'Northampton Town', tier: 'L1' },
  { key: 'peterborough-united', name: 'Peterborough United', tier: 'L1' },
  { key: 'plymouth-argyle', name: 'Plymouth Argyle', tier: 'L1' },
  { key: 'port-vale', name: 'Port Vale', tier: 'L1' },
  { key: 'reading', name: 'Reading', tier: 'L1' },
  { key: 'rotherham-united', name: 'Rotherham United', tier: 'L1' },
  { key: 'stevenage', name: 'Stevenage', tier: 'L1' },
  { key: 'stockport-county', name: 'Stockport County', tier: 'L1' },
  { key: 'wigan-athletic', name: 'Wigan Athletic', tier: 'L1' },
  { key: 'wycombe-wanderers', name: 'Wycombe Wanderers', tier: 'L1' },
  { key: 'accrington-stanley', name: 'Accrington Stanley', tier: 'L2' },
  { key: 'barnet', name: 'Barnet', tier: 'L2' },
  { key: 'barrow', name: 'Barrow', tier: 'L2' },
  { key: 'bristol-rovers', name: 'Bristol Rovers', tier: 'L2' },
  { key: 'bromley', name: 'Bromley', tier: 'L2' },
  { key: 'cambridge-united', name: 'Cambridge United', tier: 'L2' },
  { key: 'cheltenham-town', name: 'Cheltenham Town', tier: 'L2' },
  { key: 'chesterfield', name: 'Chesterfield', tier: 'L2' },
  { key: 'colchester-united', name: 'Colchester United', tier: 'L2' },
  { key: 'crawley-town', name: 'Crawley Town', tier: 'L2' },
  { key: 'crewe-alexandra', name: 'Crewe Alexandra', tier: 'L2' },
  { key: 'fleetwood-town', name: 'Fleetwood Town', tier: 'L2' },
  { key: 'gillingham', name: 'Gillingham', tier: 'L2' },
  { key: 'grimsby-town', name: 'Grimsby Town', tier: 'L2' },
  { key: 'harrogate-town', name: 'Harrogate Town', tier: 'L2' },
  { key: 'milton-keynes-dons', name: 'Milton Keynes Dons', tier: 'L2' },
  { key: 'newport-county', name: 'Newport County', tier: 'L2' },
  { key: 'notts-county', name: 'Notts County', tier: 'L2' },
  { key: 'oldham-athletic', name: 'Oldham Athletic', tier: 'L2' },
  { key: 'salford-city', name: 'Salford City', tier: 'L2' },
  { key: 'shrewsbury-town', name: 'Shrewsbury Town', tier: 'L2' },
  { key: 'swindon-town', name: 'Swindon Town', tier: 'L2' },
  { key: 'tranmere-rovers', name: 'Tranmere Rovers', tier: 'L2' },
  { key: 'walsall', name: 'Walsall', tier: 'L2' },
];

// One curated crest source per club — verified `upload.wikimedia.org` URLs (Wikipedia infobox
// crest, 2025-26). 91 of 92 clubs resolved; Mansfield Town has no entry (its Wikipedia infobox
// image lookup failed after retries) — per BADGE-001, it simply falls back to text initials.
const TeamBadgeSources: Record<string, string> = {
  'arsenal': 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  'aston-villa': 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg',
  'bournemouth': 'https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg',
  'brentford': 'https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg',
  'brighton-hove-albion': 'https://upload.wikimedia.org/wikipedia/en/d/d0/Brighton_and_Hove_Albion_FC_crest.svg',
  'burnley': 'https://upload.wikimedia.org/wikipedia/en/6/6d/Burnley_FC_Logo.svg',
  'chelsea': 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
  'crystal-palace': 'https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg',
  'everton': 'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg',
  'fulham': 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg',
  'leeds-united': 'https://upload.wikimedia.org/wikipedia/en/5/54/Leeds_United_F.C._logo.svg',
  'liverpool': 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
  'manchester-city': 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
  'manchester-united': 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
  'newcastle-united': 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',
  'nottingham-forest': 'https://upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg',
  'sunderland': 'https://upload.wikimedia.org/wikipedia/en/7/77/Logo_Sunderland.svg',
  'tottenham-hotspur': 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
  'west-ham-united': 'https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg',
  'wolverhampton-wanderers': 'https://upload.wikimedia.org/wikipedia/en/c/c9/Wolverhampton_Wanderers_FC_crest.svg',
  'birmingham-city': 'https://upload.wikimedia.org/wikipedia/en/6/68/Birmingham_City_FC_logo.svg',
  'blackburn-rovers': 'https://upload.wikimedia.org/wikipedia/en/0/0f/Blackburn_Rovers.svg',
  'bristol-city': 'https://upload.wikimedia.org/wikipedia/en/f/f5/Bristol_City_crest.svg',
  'charlton-athletic': 'https://upload.wikimedia.org/wikipedia/en/f/f5/Charlton_Athletic_FC_crest.svg',
  'coventry-city': 'https://upload.wikimedia.org/wikipedia/en/7/7b/Coventry_City_FC_crest.svg',
  'derby-county': 'https://upload.wikimedia.org/wikipedia/en/4/4a/Derby_County_crest.svg',
  'hull-city': 'https://upload.wikimedia.org/wikipedia/en/5/54/Hull_City_A.F.C._logo.svg',
  'ipswich-town': 'https://upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg',
  'leicester-city': 'https://upload.wikimedia.org/wikipedia/en/2/2d/Leicester_City_crest.svg',
  'middlesbrough': 'https://upload.wikimedia.org/wikipedia/en/2/2c/Middlesbrough_FC_crest.svg',
  'millwall': 'https://upload.wikimedia.org/wikipedia/en/9/98/Millwall_FC_crest.svg',
  'norwich-city': 'https://upload.wikimedia.org/wikipedia/en/1/17/Norwich_City_FC_logo.svg',
  'oxford-united': 'https://upload.wikimedia.org/wikipedia/en/3/3e/Oxford_United_FC_logo.svg',
  'portsmouth': 'https://upload.wikimedia.org/wikipedia/en/3/38/Portsmouth_FC_logo.svg',
  'preston-north-end': 'https://upload.wikimedia.org/wikipedia/en/8/82/Preston_North_End_FC.svg',
  'queens-park-rangers': 'https://upload.wikimedia.org/wikipedia/en/3/31/Queens_Park_Rangers_crest.svg',
  'sheffield-united': 'https://upload.wikimedia.org/wikipedia/en/9/9c/Sheffield_United_FC_logo.svg',
  'sheffield-wednesday': 'https://upload.wikimedia.org/wikipedia/en/b/b8/Sheffield_Wednesday_FC_2026_crest.svg',
  'southampton': 'https://upload.wikimedia.org/wikipedia/en/c/c9/FC_Southampton.svg',
  'stoke-city': 'https://upload.wikimedia.org/wikipedia/en/b/bf/Stoke_City_FC_crest_2026.svg',
  'swansea-city': 'https://upload.wikimedia.org/wikipedia/en/f/f9/Swansea_City_AFC_logo.svg',
  'watford': 'https://upload.wikimedia.org/wikipedia/en/e/e2/Watford.svg',
  'west-bromwich-albion': 'https://upload.wikimedia.org/wikipedia/en/8/8b/West_Bromwich_Albion.svg',
  'wrexham': 'https://upload.wikimedia.org/wikipedia/en/0/0d/Wrexham_A.F.C._Logo.svg',
  'afc-wimbledon': 'https://upload.wikimedia.org/wikipedia/en/1/1b/AFC_Wimbledon_%282020%29_logo.svg',
  'barnsley': 'https://upload.wikimedia.org/wikipedia/en/c/c9/Barnsley_FC.svg',
  'blackpool': 'https://upload.wikimedia.org/wikipedia/en/d/df/Blackpool_FC_logo.svg',
  'bolton-wanderers': 'https://upload.wikimedia.org/wikipedia/en/8/82/Bolton_Wanderers_FC_logo.svg',
  'bradford-city': 'https://upload.wikimedia.org/wikipedia/en/0/04/Bradford_City_AFC_crest.svg',
  'burton-albion': 'https://upload.wikimedia.org/wikipedia/en/9/93/Burton_Albion_FC_crest.svg',
  'cardiff-city': 'https://upload.wikimedia.org/wikipedia/en/3/3c/Cardiff_City_crest.svg',
  'doncaster-rovers': 'https://upload.wikimedia.org/wikipedia/en/c/c5/Doncaster_Rovers_F.C._logo.svg',
  'exeter-city': 'https://upload.wikimedia.org/wikipedia/en/7/71/Exeter_City_FC.svg',
  'huddersfield-town': 'https://upload.wikimedia.org/wikipedia/en/4/43/Huddersfield_Town_AFC_crest.svg',
  'leyton-orient': 'https://upload.wikimedia.org/wikipedia/en/a/a8/Leyton_Orient_F.C._logo.svg',
  'lincoln-city': 'https://upload.wikimedia.org/wikipedia/en/3/39/Lincoln_City_FC_2024_crest.svg',
  'luton-town': 'https://upload.wikimedia.org/wikipedia/en/9/9d/Luton_Town_logo.svg',
  'northampton-town': 'https://upload.wikimedia.org/wikipedia/en/2/2d/Northampton_Town_F.C._logo.svg',
  'peterborough-united': 'https://upload.wikimedia.org/wikipedia/en/9/9a/Peterborough_United_FC_crest.svg',
  'plymouth-argyle': 'https://upload.wikimedia.org/wikipedia/en/a/a8/Plymouth_Argyle_F.C._logo.svg',
  'port-vale': 'https://upload.wikimedia.org/wikipedia/en/5/5f/Port_Vale_logo.svg',
  'reading': 'https://upload.wikimedia.org/wikipedia/en/1/11/Reading_FC.svg',
  'rotherham-united': 'https://upload.wikimedia.org/wikipedia/en/4/42/Rotherham_United_F.C._svg.svg',
  'stevenage': 'https://upload.wikimedia.org/wikipedia/en/4/49/Stevenage_FC_crest.svg',
  'stockport-county': 'https://upload.wikimedia.org/wikipedia/en/4/43/Stockport_County_FC_logo_2020.svg',
  'wigan-athletic': 'https://upload.wikimedia.org/wikipedia/en/4/43/Wigan_Athletic.svg',
  'wycombe-wanderers': 'https://upload.wikimedia.org/wikipedia/en/f/fb/Wycombe_Wanderers_FC_logo.svg',
  'accrington-stanley': 'https://upload.wikimedia.org/wikipedia/en/b/ba/Accrington_Stanley_F.C._logo.svg',
  'barnet': 'https://upload.wikimedia.org/wikipedia/en/a/a2/Barnet_FC.svg',
  'barrow': 'https://upload.wikimedia.org/wikipedia/en/2/28/Barrow_AFC_logo.svg',
  'bristol-rovers': 'https://upload.wikimedia.org/wikipedia/en/4/47/Bristol_Rovers_F.C._logo.svg',
  'bromley': 'https://upload.wikimedia.org/wikipedia/en/3/35/Bromley_FC_crest.svg',
  'cambridge-united': 'https://upload.wikimedia.org/wikipedia/en/5/57/Cambridge_United_FC_crest.svg',
  'cheltenham-town': 'https://upload.wikimedia.org/wikipedia/en/c/c3/Cheltenham_Town_F.C._logo.svg',
  'chesterfield': 'https://upload.wikimedia.org/wikipedia/en/9/94/Chesterfield_FC_crest.svg',
  'colchester-united': 'https://upload.wikimedia.org/wikipedia/en/9/9c/Colchester_United_FC_crest.svg',
  'crawley-town': 'https://upload.wikimedia.org/wikipedia/en/1/11/Crawley_Town_FC_crest.svg',
  'crewe-alexandra': 'https://upload.wikimedia.org/wikipedia/en/9/9d/Crewe_Alexandra.svg',
  'fleetwood-town': 'https://upload.wikimedia.org/wikipedia/en/e/ed/Fleetwood_Town_F.C._logo.svg',
  'gillingham': 'https://upload.wikimedia.org/wikipedia/en/5/5e/FC_Gillingham_Logo.svg',
  'grimsby-town': 'https://upload.wikimedia.org/wikipedia/en/d/db/Grimsby_Town_F.C._logo.svg',
  'harrogate-town': 'https://upload.wikimedia.org/wikipedia/en/4/40/Harrogate_Town_AFC.svg',
  'milton-keynes-dons': 'https://upload.wikimedia.org/wikipedia/en/e/e5/Milton_Keynes_Dons_FC_2025_crest.svg',
  'newport-county': 'https://upload.wikimedia.org/wikipedia/en/4/44/Newport_County_AFC_crest.svg',
  'notts-county': 'https://upload.wikimedia.org/wikipedia/en/2/2e/Notts_County_Logo.svg',
  'oldham-athletic': 'https://upload.wikimedia.org/wikipedia/en/a/a2/Oldham_Athletic_AFC_%28emblem%29.svg',
  'salford-city': 'https://upload.wikimedia.org/wikipedia/en/7/70/Salford_City_F.C._new_logo.svg',
  'shrewsbury-town': 'https://upload.wikimedia.org/wikipedia/en/1/1b/Shrewsbury_Town_F.C._logo.svg',
  'swindon-town': 'https://upload.wikimedia.org/wikipedia/en/a/a3/Swindon_Town_FC.svg',
  'tranmere-rovers': 'https://upload.wikimedia.org/wikipedia/en/5/55/Tranmere_Rovers_FC_crest.svg',
  'walsall': 'https://upload.wikimedia.org/wikipedia/en/e/ef/Walsall_FC.svg',
};

// TeamConfig-shaped output (structurally compatible — no import from models.ts, avoids a
// models.ts <-> team-pools circular import). badge is the deterministic /badges/<key>.svg path
// — fixed to .svg because every curated TeamBadgeSources URl above is itself an .svg crest
// (Wikimedia's convention for football club badges); tools/fetch-team-badges.ts enforces this
// invariant at fetch time so the extension can never drift from what's actually written to disk.
const England92Teams: { key: string; name: string; badge: string }[] =
  England92.map(({ key, name }) => ({ key, name, badge: `/badges/${key}.svg` }));

export { England92, England92Teams, TeamBadgeSources };
